# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: content.accommodation.candidate.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='content.accommodation.candidate.proto',
  package='com.trivago.streaming.toolkit.proto.content.accommodation',
  syntax='proto2',
  serialized_pb=_b('\n%content.accommodation.candidate.proto\x12\x39\x63om.trivago.streaming.toolkit.proto.content.accommodation\"\x91\x03\n\tcandidate\x12T\n\x03key\x18\x02 \x01(\x0b\x32G.com.trivago.streaming.toolkit.proto.content.accommodation.candidate.PK\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0e\n\x06street\x18\x04 \x01(\t\x12\x13\n\x0bpostal_code\x18\x05 \x01(\t\x12\x10\n\x08\x64istrict\x18\x06 \x01(\t\x12\x0c\n\x04\x63ity\x18\x07 \x01(\t\x12\x0e\n\x06region\x18\x08 \x01(\t\x12\x0f\n\x07\x63ountry\x18\t \x01(\t\x12\x11\n\tlongitude\x18\n \x01(\x01\x12\x10\n\x08latitude\x18\x0b \x01(\x01\x12W\n\x04\x66lag\x18\x0c \x01(\x0b\x32I.com.trivago.streaming.toolkit.proto.content.accommodation.candidate.Flag\x1a\x1a\n\x02PK\x12\x14\n\x0c\x63\x61ndidate_id\x18\x01 \x01(\r\x1a \n\x04\x46lag\x12\x18\n\x10is_valid_geocode\x18\x01 \x01(\x08\x42~\n5com.trivago.streaming.toolkit.proto.content.candidateB\x0e\x63\x61ndidateOuterZ5com.trivago.streaming.toolkit.proto.content.candidate')
)




_CANDIDATE_PK = _descriptor.Descriptor(
  name='PK',
  full_name='com.trivago.streaming.toolkit.proto.content.accommodation.candidate.PK',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='candidate_id', full_name='com.trivago.streaming.toolkit.proto.content.accommodation.candidate.PK.candidate_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=442,
  serialized_end=468,
)

_CANDIDATE_FLAG = _descriptor.Descriptor(
  name='Flag',
  full_name='com.trivago.streaming.toolkit.proto.content.accommodation.candidate.Flag',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_valid_geocode', full_name='com.trivago.streaming.toolkit.proto.content.accommodation.candidate.Flag.is_valid_geocode', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=470,
  serialized_end=502,
)

_CANDIDATE = _descriptor.Descriptor(
  name='candidate',
  full_name='com.trivago.streaming.toolkit.proto.content.accommodation.candidate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='com.trivago.streaming.toolkit.proto.content.accommodation.candidate.key', index=0,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='com.trivago.streaming.toolkit.proto.content.accommodation.candidate.name', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='street', full_name='com.trivago.streaming.toolkit.proto.content.accommodation.candidate.street', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='postal_code', full_name='com.trivago.streaming.toolkit.proto.content.accommodation.candidate.postal_code', index=3,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='district', full_name='com.trivago.streaming.toolkit.proto.content.accommodation.candidate.district', index=4,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='city', full_name='com.trivago.streaming.toolkit.proto.content.accommodation.candidate.city', index=5,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='region', full_name='com.trivago.streaming.toolkit.proto.content.accommodation.candidate.region', index=6,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='country', full_name='com.trivago.streaming.toolkit.proto.content.accommodation.candidate.country', index=7,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='com.trivago.streaming.toolkit.proto.content.accommodation.candidate.longitude', index=8,
      number=10, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='com.trivago.streaming.toolkit.proto.content.accommodation.candidate.latitude', index=9,
      number=11, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='flag', full_name='com.trivago.streaming.toolkit.proto.content.accommodation.candidate.flag', index=10,
      number=12, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CANDIDATE_PK, _CANDIDATE_FLAG, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=502,
)

_CANDIDATE_PK.containing_type = _CANDIDATE
_CANDIDATE_FLAG.containing_type = _CANDIDATE
_CANDIDATE.fields_by_name['key'].message_type = _CANDIDATE_PK
_CANDIDATE.fields_by_name['flag'].message_type = _CANDIDATE_FLAG
DESCRIPTOR.message_types_by_name['candidate'] = _CANDIDATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

candidate = _reflection.GeneratedProtocolMessageType('candidate', (_message.Message,), dict(

  PK = _reflection.GeneratedProtocolMessageType('PK', (_message.Message,), dict(
    DESCRIPTOR = _CANDIDATE_PK,
    __module__ = 'content.accommodation.candidate_pb2'
    # @@protoc_insertion_point(class_scope:com.trivago.streaming.toolkit.proto.content.accommodation.candidate.PK)
    ))
  ,

  Flag = _reflection.GeneratedProtocolMessageType('Flag', (_message.Message,), dict(
    DESCRIPTOR = _CANDIDATE_FLAG,
    __module__ = 'content.accommodation.candidate_pb2'
    # @@protoc_insertion_point(class_scope:com.trivago.streaming.toolkit.proto.content.accommodation.candidate.Flag)
    ))
  ,
  DESCRIPTOR = _CANDIDATE,
  __module__ = 'content.accommodation.candidate_pb2'
  # @@protoc_insertion_point(class_scope:com.trivago.streaming.toolkit.proto.content.accommodation.candidate)
  ))
_sym_db.RegisterMessage(candidate)
_sym_db.RegisterMessage(candidate.PK)
_sym_db.RegisterMessage(candidate.Flag)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n5com.trivago.streaming.toolkit.proto.content.candidateB\016candidateOuterZ5com.trivago.streaming.toolkit.proto.content.candidate'))
# @@protoc_insertion_point(module_scope)
