# This workflow will deploy the GeoLocator pipeline automatically when something is pushed to
# the `master` branch.

on:
  push:
    branches:
      - master

name: Deploy GeoLocator Pipeline

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:

    # Extract the keys from repo secrets
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        # These secrets are defined in the repository settings and
        # the corresponding IAM user is geolocator-ci-cd
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1
    # This installs Python3
    - name: Setup Python environment
      uses: actions/setup-python@v1.1.1

    # Checkout the latest code
    - name: Checkout
      uses: actions/checkout@v1
    # Install dependecies and run tests
    - name: Lint with flake8
      continue-on-error: false
      run: |
        make flake8
    - name: Test with pytest
      continue-on-error: false
      run: |
        export AWS_DEFAULT_REGION=eu-west-1
        export AWS_CONFIG_FILE=~/.aws/config
        make test
    - name: Deploy Resources
      id: resources
      env:
        ENV: production
        TARGET: resources
      run: |
        make release
    - name: Deploy GeoCode
      id: geocode
      env:
        ENV: production
        TARGET: geocode
      run: |
        make release
    - name: Deploy Consolidator
      id: consolidator
      env:
        ENV: production
        TARGET: consolidator
      run: |
        make release
    - name: Deploy Router
      id: router
      env:
        ENV: production
        TARGET: router
      run: |
        make release
    # Send out a message if there is a failure in the previous steps
    - name: handle failure
      if: failure()
      id: handle-failure
      env:
        ENV: production
        NOTIFICATION_SUBJECT: "Deployment of GeoLocator stack failed!"
        NOTIFICATION_MESSAGE: "Please check https://github.com/trivago/geolocator/actions/ for more details"
      run: |
        make notify-failure